### ISSUE TITLE
Supabase Postgres v0.13.0 Checklist

### ISSUE THREAD

**Issue by dragarcia** [supabase/postgres#27]
Centralised Checklist for upcoming features/ changes to be implemented in the next version
- [x] #23 Remove readonly role
- [x] #24 Add pgjwt extension
- [x] #25 Add pgsql-http extension
- [x] #26 Add plpgsql_check extension
- [x] pljava: significant demand as well from #5 [(comment)](https://github.com/supabase/postgres/issues/5#issuecomment-632276688).
- [x] wal-g (for PITR recovery)
- [ ] ~~aws sdk (for PITR recovery, tbc)~~
- [x] daemontools (for PITR recovery)

Afterwards
- [x] Upload to AWS Marketplace
- [x] Upload to DO Marketplace
- [x] Update Docker image
- [x] Update everything else from v0.12.0
