### ISSUE TITLE
Supabase Postgres v0.14.0 Checklist

### ISSUE THREAD

**Issue by dragarcia** [supabase/postgres#32]
Centralised Checklist for upcoming features/ changes to be implemented in the next version. For any further feature requests, just comment below!
- [x] #28 Add pgcron
- [x] #31 Remove plpython
- [x] #30 Set default encoding and collation to UTF-8 for docker image
- [x] #29 Add pg-safeupdate

Afterwards
- [x] Upload to AWS Marketplace [in progress]
- [ ] Release ARM build to AWS Marketplace [in progress]
- [x] Upload to DO Marketplace
- [x] Update Docker image
- [x] Update everything else from v0.13.0

The expected release will be the end of 2020 to accommodate any more feature requests.
