### ISSUE TITLE
Set default password encryption to `scram-sha-256`

### ISSUE THREAD

**Issue by dragarcia** [supabase/postgres#65]
[reference guide](https://blog.crunchydata.com/blog/how-to-upgrade-postgresql-passwords-to-scram)

### todo
- [x] Change from `md5` to `scram-sha-256` on this [line](https://github.com/supabase/postgres/blob/develop/ansible/files/postgresql_config/postgresql.conf.j2#L95) of `postgresql.conf`.
- [x] Edit all `md5` on this [file](https://github.com/supabase/postgres/blob/develop/ansible/files/postgresql_config/pg_hba.conf.j2) to `scram-sha-256`.
- [x] Change from `md5` to `scram-sha-256` on this [line](https://github.com/supabase/postgres/blob/develop/ansible/files/pgbouncer_config/pgbouncer.ini.j2#L116) of `pgbouncer.ini`.

**Comment by Lakshmipathi** [comment]
I think this already resolved. I can see `scram-sha-256` on pg_hba.conf with these entries. @dragarcia can be marked as resolved?
